2015-06-02 10:12:15 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:12:28 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:13:30 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:13:31 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:13:31 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:14:32 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:14:58 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:17:24 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:17:41 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:17:55 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:29:45 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:29:46 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:29:46 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:29:46 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:29:47 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:29:55 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:30:12 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:30:48 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:31:50 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:34:20 main.py[line:72] ERROR 数据写入失败:(1136, "Column count doesn't match value count at row 1")
2015-06-02 10:34:34 main.py[line:72] ERROR 数据写入失败:(1136, "Column count doesn't match value count at row 1")
2015-06-02 10:35:50 main.py[line:72] ERROR 数据写入失败:(1136, "Column count doesn't match value count at row 1")
2015-06-02 11:09:55 main.py[line:72] ERROR 数据写入失败:(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\'passwd\': "\'202cb962ac59075b964b07152d234b70\'"},),birthday=\'5\xe6\x9c\x8821\',sex=\'\xe7\x94\xb7\',qq\' at line 2')
2015-06-02 18:35:33 main.py[line:96] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM \n            item' at line 9")
2015-06-02 20:32:19 main.py[line:96] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM \n            item' at line 9")
2015-06-02 20:32:24 main.py[line:96] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM \n            item' at line 9")
2015-06-02 20:32:29 main.py[line:96] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM \n            item' at line 9")
2015-06-02 20:32:32 main.py[line:96] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM \n            item' at line 9")
2015-06-02 20:32:34 main.py[line:96] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM \n            item' at line 9")
2015-06-02 20:33:18 main.py[line:96] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM \n            item' at line 9")
2015-06-02 20:33:19 main.py[line:96] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM \n            item' at line 9")
2015-06-02 20:33:21 main.py[line:96] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM \n            item' at line 9")
2015-06-02 20:34:08 main.py[line:96] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM \n            item' at line 9")
2015-06-02 20:34:12 main.py[line:96] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM \n            item' at line 9")
2015-06-02 20:34:13 main.py[line:96] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM \n            item' at line 9")
2015-06-03 10:33:47 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'isstart' in 'field list'")
2015-06-03 10:33:49 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'isstart' in 'field list'")
2015-06-03 10:34:14 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'isstart' in 'field list'")
2015-06-03 18:00:35 main.py[line:74] ERROR 数据写入失败:not enough arguments for format string
2015-06-03 18:01:45 main.py[line:74] ERROR 数据写入失败:not enough arguments for format string
2015-06-08 13:55:21 main.py[line:74] ERROR 数据写入失败:(1146, "Table 'task.partment' doesn't exist")
2015-06-08 15:14:30 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:14:33 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:14:35 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:14:36 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:14:38 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:14:42 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:14:43 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:14:48 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:14:50 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:14:52 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:15:05 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:15:06 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:15:08 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:15:09 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:15:38 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:15:38 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:15:38 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:15:38 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:15:41 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:17:15 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:17:19 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:17:21 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:17:22 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:17:24 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:17:54 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:17:56 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:18:00 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:18:56 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:19:00 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:19:05 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:19:18 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:19:19 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:19:20 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:19:21 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:19:22 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:19:24 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:19:26 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:19:27 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:19:28 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:19:45 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:25:58 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:26:06 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:26:07 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:26:09 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:26:18 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:26:23 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:27:25 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:28:19 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:28:43 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:28:43 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:28:52 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:28:54 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:28:56 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:29:39 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:29:39 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:29:39 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:29:40 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:29:43 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:29:44 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:30:35 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:30:39 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:32:44 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:32:46 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:32:47 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:32:48 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:32:49 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:32:55 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:33:15 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:34:39 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 16:08:25 main.py[line:74] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3")
2015-06-08 16:10:25 main.py[line:74] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3")
2015-06-08 16:12:08 main.py[line:74] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3")
2015-06-08 16:15:00 main.py[line:74] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3")
2015-06-08 16:23:48 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'starttime' in 'field list'")
2015-06-08 16:25:06 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'items' in 'field list'")
2015-06-08 16:25:15 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'items' in 'field list'")
2015-06-08 16:25:17 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'items' in 'field list'")
2015-06-08 16:25:20 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'items' in 'field list'")
2015-06-08 16:25:48 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'items' in 'field list'")
2015-06-08 16:26:46 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'items' in 'field list'")
2015-06-08 16:27:08 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'itype' in 'field list'")
2015-06-08 16:34:23 main.py[line:74] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3")
2015-06-08 16:53:03 main.py[line:74] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3")
2015-06-08 16:53:14 main.py[line:74] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3")
2015-06-08 16:56:06 main.py[line:74] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3")
2015-06-08 16:59:13 main.py[line:74] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3")
2015-06-10 16:20:15 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'password' in 'where clause'")
2015-06-10 16:20:22 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'password' in 'where clause'")
2015-06-10 16:21:05 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'password' in 'where clause'")
2015-06-10 16:21:09 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'password' in 'where clause'")
2015-06-10 16:21:15 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'password' in 'where clause'")
2015-06-10 16:21:56 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'password' in 'where clause'")
2015-06-10 16:29:17 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'password' in 'where clause'")
2015-06-10 20:07:11 main.py[line:98] ERROR 数据执行失败:not all arguments converted during string formatting
2015-06-10 20:07:46 main.py[line:98] ERROR 数据执行失败:not all arguments converted during string formatting
2015-06-10 20:07:47 main.py[line:98] ERROR 数据执行失败:not all arguments converted during string formatting
2015-06-10 20:07:48 main.py[line:98] ERROR 数据执行失败:not all arguments converted during string formatting
2015-06-10 20:08:24 main.py[line:98] ERROR 数据执行失败:not all arguments converted during string formatting
2015-06-10 20:08:28 main.py[line:98] ERROR 数据执行失败:not all arguments converted during string formatting
2015-06-10 20:08:34 main.py[line:98] ERROR 数据执行失败:not all arguments converted during string formatting
2015-06-10 20:28:31 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'Ui.name' in 'field list'")
2015-06-10 20:28:33 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'Ui.name' in 'field list'")
2015-06-10 20:28:34 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'Ui.name' in 'field list'")
2015-06-10 20:29:32 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'Ui.name' in 'field list'")
2015-06-10 20:29:33 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'Ui.name' in 'field list'")
2015-06-10 20:29:37 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'Ui.name' in 'field list'")
2015-06-10 20:29:40 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'Ui.name' in 'field list'")
2015-06-10 20:31:22 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'Ui.name' in 'field list'")
2015-06-11 11:13:28 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:13:56 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:14:04 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:16:14 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:16:19 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:16:58 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:17:18 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:17:37 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:20:15 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:20:20 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:20:23 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:21:28 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:22:19 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:22:41 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''WHERE 1=1'\n            ) AS t' at line 38")
2015-06-11 11:23:27 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''WHERE 1=1'\n            ) AS t' at line 38")
2015-06-11 11:23:30 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''WHERE 1=1'\n            ) AS t' at line 38")
2015-06-11 11:23:31 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''WHERE 1=1'\n            ) AS t' at line 38")
2015-06-11 11:42:09 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE 1=1 and (T.userid=18 or T.assistid=18 )\n            ORDER BY\n             ' at line 39")
2015-06-11 11:42:18 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE 1=1 and (T.userid=18 or T.assistid=18 )\n            ORDER BY\n             ' at line 39")
2015-06-11 11:42:21 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE 1=1 and (T.userid=18 or T.assistid=18 )\n            ORDER BY\n             ' at line 39")
2015-06-11 11:42:33 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE 1=1 and (T.userid=18 or T.assistid=18 )\n            ORDER BY\n             ' at line 39")
2015-06-11 11:42:35 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE 1=1 and (T.userid=18 or T.assistid=18 )\n            ORDER BY\n             ' at line 39")
2015-06-11 11:42:39 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE 1=1 and (T.userid=18 or T.assistid=18 )\n            ORDER BY\n             ' at line 39")
2015-06-11 11:43:47 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE 1=1 and (T.userid=18 or T.assistid=18 )\n            ORDER BY\n             ' at line 39")
2015-06-11 11:43:53 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE 1=1 and (T.userid=18 or T.assistid=18 )\n            ORDER BY\n             ' at line 39")
2015-06-11 11:44:01 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE 1=1 and (T.userid=18 or T.assistid=18 )\n            ORDER BY\n             ' at line 39")
2015-06-11 14:27:21 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:27:23 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:27:24 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:27:25 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:27:25 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:27:26 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:27:36 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:27:55 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:27:56 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:27:57 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:27:57 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:28:02 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:28:04 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:50:53 main.py[line:75] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'del_status=0\n        WHERE\n            id='5'' at line 5")
2015-06-11 14:52:05 main.py[line:75] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'del_status=0\n        WHERE\n            id='5'' at line 5")
2015-06-11 15:21:23 main.py[line:77] ERROR 数据写入失败:not enough arguments for format string
2015-06-11 15:22:00 main.py[line:73] ERROR 数据写入失败:not enough arguments for format string
2015-06-11 15:36:14 main.py[line:97] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 15:38:07 main.py[line:97] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 15:40:13 main.py[line:97] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 15:41:08 main.py[line:97] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:03:15 main.py[line:97] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:09:42 main.py[line:98] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:12:24 main.py[line:94] ERROR 数据执行失败:(1066, "Not unique table/alias: 'U'")
2015-06-11 16:12:27 main.py[line:94] ERROR 数据执行失败:(1066, "Not unique table/alias: 'U'")
2015-06-11 16:12:29 main.py[line:94] ERROR 数据执行失败:(1066, "Not unique table/alias: 'U'")
2015-06-11 16:15:34 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:15:36 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:15:36 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:15:37 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:15:38 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:15:39 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:15:40 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:15:41 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:15:44 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:15:45 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:15:46 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:15:46 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:15:53 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:16:13 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:16:15 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:16:16 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:16:19 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:16:28 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:16:34 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:19:29 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:19:30 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:19:31 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:19:31 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:19:31 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:19:32 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:19:32 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:20:42 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:21:00 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-12 10:00:27 main.py[line:94] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM\n            item AS I\n            LEFT OUTER JOIN user AS U on I.userid = U' at line 11")
2018-01-18 16:04:54 main.py[line:97] ERROR 数据执行失败:'long' object is not iterable
2018-01-18 16:39:40 main.py[line:97] ERROR 数据执行失败:'long' object is not iterable
2018-01-18 16:41:23 main.py[line:97] ERROR 数据执行失败:'long' object is not iterable
2018-01-18 17:22:34 main.py[line:97] ERROR 数据执行失败:'long' object is not iterable
2018-01-18 17:23:59 main.py[line:73] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-18 17:24:02 main.py[line:73] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-18 17:24:02 main.py[line:73] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-18 17:24:03 main.py[line:73] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-18 17:24:03 main.py[line:73] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-18 17:24:03 main.py[line:73] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-18 17:24:03 main.py[line:73] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-18 17:24:04 main.py[line:73] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-18 17:24:04 main.py[line:73] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-18 17:24:05 main.py[line:73] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-18 17:24:05 main.py[line:73] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-18 17:24:05 main.py[line:73] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-18 17:24:05 main.py[line:73] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-18 17:24:06 main.py[line:73] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-18 17:24:07 main.py[line:73] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-18 17:24:07 main.py[line:73] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-18 17:24:07 main.py[line:73] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-18 17:24:17 main.py[line:73] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-18 17:24:19 main.py[line:73] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-18 17:24:20 main.py[line:73] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-18 17:24:20 main.py[line:73] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-18 17:24:27 main.py[line:73] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-18 17:41:30 main.py[line:97] ERROR 数据执行失败:'long' object is not iterable
2018-01-18 17:48:18 main.py[line:97] ERROR 数据执行失败:not all arguments converted during string formatting
2018-01-18 17:48:18 main.py[line:97] ERROR 数据执行失败:not all arguments converted during string formatting
2018-01-18 17:48:21 main.py[line:97] ERROR 数据执行失败:not all arguments converted during string formatting
2018-01-18 17:48:21 main.py[line:97] ERROR 数据执行失败:not all arguments converted during string formatting
2018-01-18 17:48:28 main.py[line:97] ERROR 数据执行失败:not all arguments converted during string formatting
2018-01-18 17:48:28 main.py[line:97] ERROR 数据执行失败:not all arguments converted during string formatting
2018-01-18 17:48:33 main.py[line:97] ERROR 数据执行失败:not all arguments converted during string formatting
2018-01-18 17:48:33 main.py[line:97] ERROR 数据执行失败:not all arguments converted during string formatting
2018-01-19 14:18:50 main.py[line:90] ERROR 数据库连接失败:(2003, "Can't connect to MySQL server on 'localhost' (10061)")
2018-01-19 14:19:00 main.py[line:90] ERROR 数据库连接失败:(2003, "Can't connect to MySQL server on 'localhost' (10061)")
2018-01-19 14:19:04 main.py[line:90] ERROR 数据库连接失败:(2003, "Can't connect to MySQL server on 'localhost' (10061)")
2018-01-19 14:19:09 main.py[line:90] ERROR 数据库连接失败:(2003, "Can't connect to MySQL server on 'localhost' (10061)")
2018-01-19 14:19:18 main.py[line:90] ERROR 数据库连接失败:(2003, "Can't connect to MySQL server on 'localhost' (10061)")
2018-01-19 14:20:39 main.py[line:90] ERROR 数据库连接失败:(2003, "Can't connect to MySQL server on '192.168.50.139' (10060)")
2018-01-19 14:21:00 main.py[line:90] ERROR 数据库连接失败:(2003, "Can't connect to MySQL server on '192.168.50.139' (10060)")
2018-01-19 14:21:45 main.py[line:90] ERROR 数据库连接失败:(2003, "Can't connect to MySQL server on '192.168.50.139' (10060)")
2018-01-19 14:22:13 main.py[line:90] ERROR 数据库连接失败:(2003, "Can't connect to MySQL server on '192.168.50.139' (10060)")
2018-01-19 17:17:26 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'H.user' in 'field list'")
2018-01-19 17:17:57 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'H.user' in 'field list'")
2018-01-19 17:17:59 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'H.user' in 'field list'")
2018-01-19 17:18:01 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'H.user' in 'field list'")
2018-01-19 17:18:03 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'H.user' in 'field list'")
2018-01-19 17:18:04 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'H.user' in 'field list'")
2018-01-19 17:18:38 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'H.user' in 'field list'")
2018-01-19 17:22:38 main.py[line:98] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM\n            hosts as H' at line 10")
2018-01-19 17:22:44 main.py[line:98] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM\n            hosts as H' at line 10")
2018-01-19 17:37:59 main.py[line:74] ERROR 数据写入失败:not enough arguments for format string
2018-01-19 17:38:25 main.py[line:74] ERROR 数据写入失败:(1054, "Unknown column 'ip' in 'field list'")
2018-01-19 17:38:44 main.py[line:74] ERROR 数据写入失败:(1062, "Duplicate entry '0' for key 'PRIMARY'")
2018-01-19 17:41:45 main.py[line:74] ERROR 数据写入失败:(1062, "Duplicate entry '0' for key 'PRIMARY'")
2018-01-22 09:25:39 main.py[line:75] ERROR 数据写入失败:not enough arguments for format string
2018-01-22 09:26:21 main.py[line:75] ERROR 数据写入失败:not enough arguments for format string
2018-01-22 09:26:44 main.py[line:75] ERROR 数据写入失败:not enough arguments for format string
2018-01-22 09:26:57 main.py[line:75] ERROR 数据写入失败:not enough arguments for format string
2018-01-22 17:45:05 DB.py[line:39] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'distributionversion='7.4.1708',kernel='3.10.0-693.el7.x86_64',memory=472,distrib' at line 2")
2018-01-22 18:03:14 DB.py[line:39] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-22 18:03:14 DB.py[line:39] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-23 09:56:27 main.py[line:100] ERROR 数据执行失败:not all arguments converted during string formatting
2018-01-23 09:56:27 main.py[line:100] ERROR 数据执行失败:not all arguments converted during string formatting
2018-01-23 11:17:57 main.py[line:77] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-23 11:18:18 main.py[line:77] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-23 11:18:33 main.py[line:77] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-23 11:19:21 main.py[line:77] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-23 11:19:53 main.py[line:77] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-23 11:27:42 main.py[line:100] ERROR 数据执行失败:'long' object is not iterable
2018-01-23 11:28:01 main.py[line:77] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-23 15:03:05 main.py[line:100] ERROR 数据执行失败:not all arguments converted during string formatting
2018-01-23 15:03:48 main.py[line:100] ERROR 数据执行失败:not all arguments converted during string formatting
2018-01-23 15:03:50 main.py[line:100] ERROR 数据执行失败:not all arguments converted during string formatting
2018-01-23 15:04:42 main.py[line:100] ERROR 数据执行失败:not all arguments converted during string formatting
2018-01-23 15:05:00 main.py[line:100] ERROR 数据执行失败:not all arguments converted during string formatting
2018-01-23 15:11:13 main.py[line:100] ERROR 数据执行失败:not all arguments converted during string formatting
2018-01-23 15:18:03 main.py[line:100] ERROR 数据执行失败:not all arguments converted during string formatting
2018-01-23 15:20:16 main.py[line:100] ERROR 数据执行失败:not all arguments converted during string formatting
2018-01-23 15:27:04 main.py[line:100] ERROR 数据执行失败:not all arguments converted during string formatting
2018-01-23 15:35:26 main.py[line:77] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-23 15:37:19 main.py[line:77] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-23 15:37:50 main.py[line:77] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-23 15:38:58 main.py[line:77] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-23 15:38:59 main.py[line:77] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-23 15:41:33 main.py[line:77] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-23 15:41:48 main.py[line:77] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-23 15:42:26 main.py[line:77] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-23 16:08:46 main.py[line:77] ERROR 数据写入失败:not all arguments converted during string formatting
2018-01-23 16:33:00 main.py[line:100] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.name      \n        FROM\n            item as I' at line 3")
2018-01-23 17:21:11 main.py[line:100] ERROR 数据执行失败:not all arguments converted during string formatting
2018-01-23 17:41:27 main.py[line:100] ERROR 数据执行失败:not all arguments converted during string formatting
2018-01-23 18:01:02 main.py[line:100] ERROR 数据执行失败:not all arguments converted during string formatting
2018-01-25 09:37:02 main.py[line:100] ERROR 数据执行失败:not all arguments converted during string formatting
